//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuzeyYeli.WinForm.CategoryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryServiceReference.IServiceOf_CategoryDTO")]
    public interface IServiceOf_CategoryDTO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/List", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/ListResponse")]
        System.Collections.Generic.List<KuzeyYeliDTO.CategoryDTO> List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/List", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/ListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<KuzeyYeliDTO.CategoryDTO>> ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/Insert", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/InsertResponse")]
        bool Insert(KuzeyYeliDTO.CategoryDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/Insert", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(KuzeyYeliDTO.CategoryDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/UpdateResponse")]
        bool Update(KuzeyYeliDTO.CategoryDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(KuzeyYeliDTO.CategoryDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/DeleteResponse")]
        bool Delete(KuzeyYeliDTO.CategoryDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_CategoryDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_CategoryDTO/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(KuzeyYeliDTO.CategoryDTO dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_CategoryDTOChannel : KuzeyYeli.WinForm.CategoryServiceReference.IServiceOf_CategoryDTO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_CategoryDTOClient : System.ServiceModel.ClientBase<KuzeyYeli.WinForm.CategoryServiceReference.IServiceOf_CategoryDTO>, KuzeyYeli.WinForm.CategoryServiceReference.IServiceOf_CategoryDTO {
        
        public ServiceOf_CategoryDTOClient() {
        }
        
        public ServiceOf_CategoryDTOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_CategoryDTOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_CategoryDTOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_CategoryDTOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<KuzeyYeliDTO.CategoryDTO> List() {
            return base.Channel.List();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<KuzeyYeliDTO.CategoryDTO>> ListAsync() {
            return base.Channel.ListAsync();
        }
        
        public bool Insert(KuzeyYeliDTO.CategoryDTO dto) {
            return base.Channel.Insert(dto);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(KuzeyYeliDTO.CategoryDTO dto) {
            return base.Channel.InsertAsync(dto);
        }
        
        public bool Update(KuzeyYeliDTO.CategoryDTO dto) {
            return base.Channel.Update(dto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(KuzeyYeliDTO.CategoryDTO dto) {
            return base.Channel.UpdateAsync(dto);
        }
        
        public bool Delete(KuzeyYeliDTO.CategoryDTO dto) {
            return base.Channel.Delete(dto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(KuzeyYeliDTO.CategoryDTO dto) {
            return base.Channel.DeleteAsync(dto);
        }
    }
}
