//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuzeyYeli.WinForm.SupplierServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupplierServiceReference.IServiceOf_SupplierDTO")]
    public interface IServiceOf_SupplierDTO {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/List", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/ListResponse")]
        KuzeyYeliDTO.SupplierDTO[] List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/List", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/ListResponse")]
        System.Threading.Tasks.Task<KuzeyYeliDTO.SupplierDTO[]> ListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/Insert", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/InsertResponse")]
        bool Insert(KuzeyYeliDTO.SupplierDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/Insert", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/InsertResponse")]
        System.Threading.Tasks.Task<bool> InsertAsync(KuzeyYeliDTO.SupplierDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/UpdateResponse")]
        bool Update(KuzeyYeliDTO.SupplierDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/Update", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(KuzeyYeliDTO.SupplierDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/DeleteResponse")]
        bool Delete(KuzeyYeliDTO.SupplierDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOf_SupplierDTO/Delete", ReplyAction="http://tempuri.org/IServiceOf_SupplierDTO/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(KuzeyYeliDTO.SupplierDTO dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOf_SupplierDTOChannel : KuzeyYeli.WinForm.SupplierServiceReference.IServiceOf_SupplierDTO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOf_SupplierDTOClient : System.ServiceModel.ClientBase<KuzeyYeli.WinForm.SupplierServiceReference.IServiceOf_SupplierDTO>, KuzeyYeli.WinForm.SupplierServiceReference.IServiceOf_SupplierDTO {
        
        public ServiceOf_SupplierDTOClient() {
        }
        
        public ServiceOf_SupplierDTOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOf_SupplierDTOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_SupplierDTOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOf_SupplierDTOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KuzeyYeliDTO.SupplierDTO[] List() {
            return base.Channel.List();
        }
        
        public System.Threading.Tasks.Task<KuzeyYeliDTO.SupplierDTO[]> ListAsync() {
            return base.Channel.ListAsync();
        }
        
        public bool Insert(KuzeyYeliDTO.SupplierDTO dto) {
            return base.Channel.Insert(dto);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAsync(KuzeyYeliDTO.SupplierDTO dto) {
            return base.Channel.InsertAsync(dto);
        }
        
        public bool Update(KuzeyYeliDTO.SupplierDTO dto) {
            return base.Channel.Update(dto);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(KuzeyYeliDTO.SupplierDTO dto) {
            return base.Channel.UpdateAsync(dto);
        }
        
        public bool Delete(KuzeyYeliDTO.SupplierDTO dto) {
            return base.Channel.Delete(dto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(KuzeyYeliDTO.SupplierDTO dto) {
            return base.Channel.DeleteAsync(dto);
        }
    }
}
